### ISSUE TITLE
Software decoder crashes

### ISSUE THREAD

**Issue by cgutman** [GTMoogle/StreamTheater#1]
Can you post a full stack trace of the crash? I'd like to see what call it's making when the crash happens (and if it's on the decode or the draw side of things).

**Comment by GTMoogle** [comment]
Sorry, I missed the e-mail notification git-hub sent me. I'm trying to reproduce the crash.  The crash might have been a product of my code, but the error from ffmpeg right before it was 'invalid_data', which is what I wanted to debug.  I managed to get ffmpeg compiling under cygwin, and then saw this e-mail.

At the moment I'm having an issue reproducing the crash because the decoder's setup() call isn't getting called after I do nvconn.start().  It was being called consistently before, no idea why I'm having this issue now.  >_<

**Comment by GTMoogle** [comment]
Ok, crash log and ndk-stack: http://pastebin.com/i5cTUr56

**Comment by cgutman** [comment]
It looks like that crash is on the rendering side. The stack trace is strangely useless but my guess is that the real crash is in avpicture_layout() when it's copying the pixels from the resampled RGB frame into the surface buffer. I've seen this happen when the surface format or size was wrong.

Hypothetical call stack:
??? (avpicture_layout)
nv_avc_dec.c:249 (render_rgb_to_buffer)
nv_avc_dec.c:321 (nv_avc_redraw)
AndroidCpuDecoderRenderer.java:195 (run)


I would add calls to ANativeWindow_getFormat, ANativeWindow_getWidth, and ANativeWindow_getHeight in nv_avc_redraw and see what it thinks the format and dimensions are.

**Comment by GTMoogle** [comment]
Ok, not sure if I've just done something really dumb while recompiling ffmpeg or not, but the behavior is the same as before.
I threw log statements all over the place, and it looks like all the arguments are mangled when avcodec_decode_video2 is called.

Arguments right before the call in stream theater:
ctx: 0xa1644000 df: 0x97eede00 &gp: 0x969d5a38 pkt: 0x99fd5008
and the contents of the avpkt:
ST size: 26 si: 0 flags: 00000000 dur: 0 sde: 0 pos: -1 data: 0000000167640032

The arguments from inside the ffmpeg function:
ctx: 0x969d5934 df: 0x0 &gp: 0x63203256 pkt: 0x203a7874
And of course that packet is garbage:
size: -1768072908 si: 0 flags: 76613256 dur: 544500592 sde: 1702521203 pos: 3474586723192479802 data: 3039323769732038

I'm having a hard time googling an answer for what's going on here.  I don't know whether the addresses are supposed to stay the same when you're calling a library function, but the packet's definitely nonsense of the random-memory variety.

I actually just noticed the ctx from ffmpeg is close-but-not-quite to the 'got_pic' address.

Any ideas, or am I on a wild goose chase?
(This was always broken, even on kitkat)

Looks like you're right about avpicture_layout causing the actual crash though:
05-27 09:11:15.510: E/NVAVCDEC(5560): avpicture_layout rgb 0x98acbe00 1280 720 0x9f800000 3686400
05-27 09:11:15.510: A/libc(5560): Fatal signal 7 (SIGBUS), code 2, fault addr 0x9f811000 in tid 8650 (Video - Rendere)

I'll check the ANativeWindow stuff in an hour or so when I get back home.

Thanks

**Comment by GTMoogle** [comment]
Format = 1 width = 1 height = 1.  Nice.  

*inserts call to Oculus defined surfacetexture wrapper function SetDefaultBufferSize which was never called anywhere in a grep of the entire oculus SDK*

It works!  By god it works!

Well, I guess my weird function parameters were irrelevant, seems to be software decoding just fine.  Now to see if this fixes the hardware issue.

I can't thank you enough.

**Comment by GTMoogle** [comment]
Nope, hardware decoder issue isn't solved by that, but *some* solution exists, so I'll take it. (I actually feel a little better that the hardware issue wasn't so simple, since I spent so much time on it...)

**Comment by cgutman** [comment]
The rendering stuff on the MediaCodec side seems like magic to me. The codec does some internal manipulation of the surface to make it suitable for rendering. I'm trying to find something in AOSP that could shed some light on what it's doing to the surface.

If you've got any other Lollipop devices, I'd try hardware decoding on those to see if something shows up in the log (or it works). You could also try removing stuff from the frame rendering code until you get a really simple repro case. If you can repro on a Tegra K1 device, you could try Tegra Graphics Debugger. Maybe there's a similar tool for Qualcomm devices.

I can try to repro with my Nexus 9 .I'm away from my LAN with my GFE PC, so I'd need a version that can connect to a manually entered IP address (and works without a GearVR).

**Comment by GTMoogle** [comment]
I keep assuming the oculus libraries will just completely fail to work on anything other than the note4 and s6, but I actually already know that's wrong - someone put their VR app on the play store a long time back and it started on my nexus 5 (have since upgraded to note 4 so it's not laying around) but crashed after some graphical glitches in the intro.  I'll see what I can dig up for hardware.

I plan to get the menu interface, settings, and manual PC entry in eventually, but it's a couple items down my todo list (partly because I'm going to have to write a UI library, because that doesn't quite exist in VR yet).  At least the big one has a workaround (For now I'm just going to blacklist OMX.qcom and OMX.SEC if os == lollipop).

I'll check out the qualcomm tools soon.

How do I send you a case of beer (or whatever you like)?

**Comment by GTMoogle** [comment]
The latency with the software decoder is pretty bad.  I saw a reference somewhere that software decoding might be faster than hardware for small video sizes.  Any tips?

**Comment by cgutman** [comment]
I was worried that performance would be bad on CPU decoding. You could try 720p30 instead of 720p60. That tends to work best with CPU decoding.

If you'd rather tinker with it, try tweaking the CPU decoding code. https://github.com/GTMoogle/StreamTheater/blob/master/src/com/limelight/binding/video/AndroidCpuDecoderRenderer.java#L94

Try changing the perfLevel to MID_PERF to see if it's just too many threads causing extra latency (1 thread = 1 frame of latency). You could also try the SLICE_THREADING flag which should work since GFE 2.4 with 4 threads (slice threading should introduce no additional latency).

**Comment by GTMoogle** [comment]
I really thought it would be ok at higher performance levels, but it really can't handle anything other than LOW_PERF.  Even the difference between the theater environment and the featureless black void made it stutter twice as often. 

Well, at least it can stream media, but this is sad.  I'm trying to download the qcom sdk now.

**Comment by GTMoogle** [comment]
Got it.  The cinema code wasn't updating the screen because it was checking to make sure the timestamps were different on the SurfaceTexture.  Those are set by updateTexImage, and they should come from Mediacodec.

The reasons I can see for kitkat working and not lollipop are either kitkat's mediacodec was making up for a missing/broken timestamp on the stream and lollipop stopped being nice, or lollipop broke something.  I'll try to look into it more later, but I have a fix finally.

**Comment by cgutman** [comment]
Nice find. FYI, I left a comment on your commit. Planning to release a new version soon?

**Comment by GTMoogle** [comment]
Yeah, thank you.  I've changed it now, just haven't pushed yet.  I'll get a
new version out soon, but the oculus 0.6.0 merge broke some stuff, so I've
had to squeeze in work around watching my daughter all day.  It's almost
ready.  Maybe tomorrow morning.
